# Generated by Django 5.0.4 on 2025-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_tracking_id_purchases_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='payment_complete',
        ),
        migrations.AddField(
            model_name='purchases',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
    ]
