# Generated by Django 5.0.4 on 2025-07-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_purchases_payment_complete_purchases_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='tracking_id',
        ),
    ]
