# Generated by Django 5.0.4 on 2025-07-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_booking_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
