# Generated by Django 5.0.4 on 2025-07-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_end_date_booking_equipment_booking_quantity_and_more'),
        ('payments', '0002_purchasespayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='BookingPayment',
        ),
    ]
