# Generated by Django 5.0.4 on 2025-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_payment_bookingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchasespayment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
