# Generated by Django 5.0.4 on 2025-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentintent_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
