# Generated by Django 5.0.4 on 2025-07-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentintent_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasespayment',
            name='receipt',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
