# Generated by Django 5.0.4 on 2025-07-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_purchasespayment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasespayment',
            name='receipt',
        ),
    ]
