# Generated by Django 5.0.4 on 2025-07-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_purchasespayment_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentintent',
            old_name='booking_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='paymentintent',
            old_name='booking_start_date',
            new_name='start_date',
        ),
    ]
