# Generated by Django 5.0.4 on 2025-06-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_image_url_alter_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
